### ISSUE TITLE
Passthru parameter which should return services that need fix

### ISSUE THREAD

**Issue by VectorBCO** [dronovvictor/windows-path-enumerate#19]
Idea: run script with passthru parameter and analyze output not in a file but in a console
Output should be an array with list of objects with Service/Application name, Type, Current path, Expected path
This will allow to use current script in SCCM to verify is fix needed or not

**Comment by Lostinear** [comment]
I have been trying to get this for ages. I am no Powershell expert by a long way and I desperately want to have a baseline that remediates using your script if it finds the issues. Currently I use 
$value = cmd /c  'wmic service get name,displayname,pathname,startmode |findstr /i "auto" |findstr /i /v "c:\windows\\" |findstr /i /v """'

if ($value -like "* *") 
   {
   1
   }
   else
   {
   0
   }
But this does not find issues with Uninstall and Env. So please please please get this ability :)

**Comment by VectorBCO** [comment]
@Lostinear, you can try script from this [release](https://github.com/VectorBCO/windows-path-enumerate/releases/tag/v3.5)

**Comment by Lostinear** [comment]
Awesome!!!!
